// Code generated by go generate; DO NOT EDIT.
package pgmb

import (
	sq "github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
)

// AreaQueryFunc can be chained together to modify a AreaQuery
type AreaQueryFunc func(AreaQuery) AreaQuery

// AreaQuery is a queryer for Area data
type AreaQuery struct {
	db         DB
	builder    sq.SelectBuilder
	processors []AreaCollectionProcessor
}

// Areas is the constructor for AreaQuery
func Areas(db DB) AreaQuery {
	q := AreaQuery{
		db:      db,
		builder: AreaSelect(),
	}
	return q
}

// AreaCollection is a slice of Area
type AreaCollection []*Area

// AreaCollectionProcessor is a function which modifies each element in a AreaCollection
// (typically by populting additional data on it)
type AreaCollectionProcessor func(DB, AreaCollection) error

// Select can be used to replace AreaSelect() with a different squirrel.SelectBuilder
// to pull different fields or join data differently.
func (q AreaQuery) Select(b sq.SelectBuilder) AreaQuery {
	q.builder = b
	return q
}

// Where adds an additional where clause to the query
func (q AreaQuery) Where(cmd string, args ...interface{}) AreaQuery {
	q.builder = q.builder.Where(cmd, args...)
	return q
}

// OrderBy adjusts the ordering criteria for the query
func (q AreaQuery) OrderBy(cmd string) AreaQuery {
	q.builder = q.builder.OrderBy(cmd)
	return q
}

// All returns all results from the query
func (q AreaQuery) All() (results AreaCollection, err error) {
	results = make(AreaCollection, 0)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "AreaQuery.All() failed to populate AreaCollection.")
		return
	}
	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over AreaCollection.")
		}
	}
	return
}

// One returns a single result from the query
func (q AreaQuery) One() (result *Area, err error) {
	results := make(AreaCollection, 0, 1)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "AreaQuery.One() failed to populate initial result set.")
		return
	}

	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over AreaCollection.")
			return
		}
	}

	if len(results) > 0 {
		result = results[0]
	}

	return result, nil
}
