// Code generated by go generate; DO NOT EDIT.
package pgmb

import (
	"strings"
	"github.com/pkg/errors"
)

// ArtistCreditQuery is a queryer for ArtistCredit data
type ArtistCreditQuery struct {
	db      DB
	builder SelectBuilder
	processors []ArtistCreditCollectionProcessor
}

// ArtistCredits is the constructor for ArtistCreditQuery
func ArtistCredits(db DB, columns ...string) ArtistCreditQuery {

	var selectClause string
	if len(columns) > 0 {
		selectClause = strings.Join(columns, ", ")
	} else {
		selectClause = "id, name, artist_count, ref_count, ARRAY(SELECT n.artist FROM artist_credit_name n WHERE n.artist_credit = artist_credit.id) as artist_ids"
	}

	q := ArtistCreditQuery{
		db:      db,
		builder: SelectBuilder{}.Select(selectClause).From("artist_credit"),
	}
	return q
}

// ArtistCreditCollection is a slice of ArtistCredit
type ArtistCreditCollection []*ArtistCredit

// ArtistCreditCollectionProcessor is a function which modifies each element in a ArtistCreditCollection
// (typically by populting additional data on it)
type ArtistCreditCollectionProcessor func(DB, ArtistCreditCollection) error

// Select adjusts the columns returned from the query
func (q ArtistCreditQuery) Select(columns string) ArtistCreditQuery {
	q.builder = q.builder.Select(columns)
	return q
}

// Where adds an additional where clause to the query
func (q ArtistCreditQuery) Where(cmd string, args ...interface{}) ArtistCreditQuery {
	q.builder = q.builder.Where(cmd, args...)
	return q
}

// OrderBy adjusts the ordering criteria for the query
func (q ArtistCreditQuery) OrderBy(cmd string) ArtistCreditQuery {
	q.builder = q.builder.OrderBy(cmd)
	return q
}

// All returns all results from the query
func (q ArtistCreditQuery) All() (results ArtistCreditCollection, err error) {
	results = make(ArtistCreditCollection, 0)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ArtistCreditQuery.All() failed to populate ArtistCreditCollection.")
		return
	}
	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ArtistCreditCollection.")
		}
	}
	return
}

// One returns a single result from the query
func (q ArtistCreditQuery) One() (result *ArtistCredit, err error) {
	results := make(ArtistCreditCollection, 0, 1)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ArtistCreditQuery.One() failed to populate initial result set.")
		return
	}

	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ArtistCreditCollection.")
			return
		}
	}

	if len(results) > 0 {
		result = results[0]
	}

	return result, nil
}
