// Code generated by go generate; DO NOT EDIT.
package pgmb

import (
	sq "github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
)

// ArtistCreditQueryFunc can be chained together to modify a ArtistCreditQuery
type ArtistCreditQueryFunc func(ArtistCreditQuery) ArtistCreditQuery

// ArtistCreditQuery is a queryer for ArtistCredit data
type ArtistCreditQuery struct {
	db         DB
	builder    sq.SelectBuilder
	processors []ArtistCreditCollectionProcessor
}

// ArtistCredits is the constructor for ArtistCreditQuery
func ArtistCredits(db DB) ArtistCreditQuery {
	q := ArtistCreditQuery{
		db:      db,
		builder: ArtistCreditSelect(),
	}
	return q
}

// ArtistCreditCollection is a slice of ArtistCredit
type ArtistCreditCollection []*ArtistCredit

// ArtistCreditCollectionProcessor is a function which modifies each element in a ArtistCreditCollection
// (typically by populting additional data on it)
type ArtistCreditCollectionProcessor func(DB, ArtistCreditCollection) error

// From sets the table being queried
func (q ArtistCreditQuery) From(name string) ArtistCreditQuery {
	q.builder = q.builder.From(name)
	return q
}

// Where adds an additional where clause to the query
func (q ArtistCreditQuery) Where(cmd string, args ...interface{}) ArtistCreditQuery {
	q.builder = q.builder.Where(cmd, args...)
	return q
}

// OrderBy adjusts the ordering criteria for the query
func (q ArtistCreditQuery) OrderBy(cmd string) ArtistCreditQuery {
	q.builder = q.builder.OrderBy(cmd)
	return q
}

// All returns all results from the query
func (q ArtistCreditQuery) All() (results ArtistCreditCollection, err error) {
	results = make(ArtistCreditCollection, 0)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ArtistCreditQuery.All() failed to populate ArtistCreditCollection.")
		return
	}
	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ArtistCreditCollection.")
		}
	}
	return
}

// One returns a single result from the query
func (q ArtistCreditQuery) One() (result *ArtistCredit, err error) {
	results := make(ArtistCreditCollection, 0, 1)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ArtistCreditQuery.One() failed to populate initial result set.")
		return
	}

	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ArtistCreditCollection.")
			return
		}
	}

	if len(results) > 0 {
		result = results[0]
	}

	return result, nil
}
