// Code generated by go generate; DO NOT EDIT.
package pgmb

import (
	"strings"
	"github.com/pkg/errors"
)

// ReleaseQuery is a queryer for Release data
type ReleaseQuery struct {
	db      DB
	builder SelectBuilder
	processors []ReleaseCollectionProcessor
}

// Releases is the constructor for ReleaseQuery
func Releases(db DB, columns ...string) ReleaseQuery {

	var selectClause string
	if len(columns) > 0 {
		selectClause = strings.Join(columns, ", ")
	} else {
		selectClause = "id, gid, name, artist_credit, release_group, status, packaging, comment, barcode, quality"
	}

	q := ReleaseQuery{
		db:      db,
		builder: SelectBuilder{}.Select(selectClause).From("release"),
	}
	return q
}

// ReleaseCollection is a slice of Release
type ReleaseCollection []*Release

// ReleaseCollectionProcessor is a function which modifies each element in a ReleaseCollection
// (typically by populting additional data on it)
type ReleaseCollectionProcessor func(DB, ReleaseCollection) error

// Select adjusts the columns returned from the query
func (q ReleaseQuery) Select(columns string) ReleaseQuery {
	q.builder = q.builder.Select(columns)
	return q
}

// Where adds an additional where clause to the query
func (q ReleaseQuery) Where(cmd string, args ...interface{}) ReleaseQuery {
	q.builder = q.builder.Where(cmd, args...)
	return q
}

// OrderBy adjusts the ordering criteria for the query
func (q ReleaseQuery) OrderBy(cmd string) ReleaseQuery {
	q.builder = q.builder.OrderBy(cmd)
	return q
}

// All returns all results from the query
func (q ReleaseQuery) All() (results ReleaseCollection, err error) {
	results = make(ReleaseCollection, 0)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ReleaseQuery.All() failed to populate ReleaseCollection.")
		return
	}
	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ReleaseCollection.")
		}
	}
	return
}

// One returns a single result from the query
func (q ReleaseQuery) One() (result *Release, err error) {
	results := make(ReleaseCollection, 0, 1)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ReleaseQuery.One() failed to populate initial result set.")
		return
	}

	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ReleaseCollection.")
			return
		}
	}

	if len(results) > 0 {
		result = results[0]
	}

	return result, nil
}
