// Code generated by go generate; DO NOT EDIT.
package pgmb

import (
	sq "github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
)

// ReleaseGroupQueryFunc can be chained together to modify a ReleaseGroupQuery
type ReleaseGroupQueryFunc func(ReleaseGroupQuery) ReleaseGroupQuery

// ReleaseGroupQuery is a queryer for ReleaseGroup data
type ReleaseGroupQuery struct {
	db         DB
	builder    sq.SelectBuilder
	processors []ReleaseGroupCollectionProcessor
}

// ReleaseGroups is the constructor for ReleaseGroupQuery
func ReleaseGroups(db DB) ReleaseGroupQuery {
	q := ReleaseGroupQuery{
		db:      db,
		builder: ReleaseGroupSelect(),
	}
	return q
}

// ReleaseGroupCollection is a slice of ReleaseGroup
type ReleaseGroupCollection []*ReleaseGroup

// ReleaseGroupCollectionProcessor is a function which modifies each element in a ReleaseGroupCollection
// (typically by populting additional data on it)
type ReleaseGroupCollectionProcessor func(DB, ReleaseGroupCollection) error

// Select can be used to replace ReleaseGroupSelect() with a different squirrel.SelectBuilder
// to pull different fields or join data differently.
func (q ReleaseGroupQuery) Select(b sq.SelectBuilder) ReleaseGroupQuery {
	q.builder = b
	return q
}

// Where adds an additional where clause to the query
func (q ReleaseGroupQuery) Where(cmd string, args ...interface{}) ReleaseGroupQuery {
	q.builder = q.builder.Where(cmd, args...)
	return q
}

// OrderBy adjusts the ordering criteria for the query
func (q ReleaseGroupQuery) OrderBy(cmd string) ReleaseGroupQuery {
	q.builder = q.builder.OrderBy(cmd)
	return q
}

// All returns all results from the query
func (q ReleaseGroupQuery) All() (results ReleaseGroupCollection, err error) {
	results = make(ReleaseGroupCollection, 0)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ReleaseGroupQuery.All() failed to populate ReleaseGroupCollection.")
		return
	}
	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ReleaseGroupCollection.")
		}
	}
	return
}

// One returns a single result from the query
func (q ReleaseGroupQuery) One() (result *ReleaseGroup, err error) {
	results := make(ReleaseGroupCollection, 0, 1)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ReleaseGroupQuery.One() failed to populate initial result set.")
		return
	}

	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ReleaseGroupCollection.")
			return
		}
	}

	if len(results) > 0 {
		result = results[0]
	}

	return result, nil
}
