// Code generated by go generate; DO NOT EDIT.
package pgmb

import (
	"strings"
	"github.com/pkg/errors"
)

// ReleaseGroupQuery is a queryer for ReleaseGroup data
type ReleaseGroupQuery struct {
	db      DB
	builder SelectBuilder
	processors []ReleaseGroupCollectionProcessor
}

// ReleaseGroups is the constructor for ReleaseGroupQuery
func ReleaseGroups(db DB, columns ...string) ReleaseGroupQuery {

	var selectClause string
	if len(columns) > 0 {
		selectClause = strings.Join(columns, ", ")
	} else {
		selectClause = "id, gid, name, type, artist_credit, comment, ARRAY(SELECT j.secondary_type FROM release_group_secondary_type_join j WHERE j.release_group = release_group.id) as secondary_type_ids"
	}

	q := ReleaseGroupQuery{
		db:      db,
		builder: SelectBuilder{}.Select(selectClause).From("release_group"),
	}
	return q
}

// ReleaseGroupCollection is a slice of ReleaseGroup
type ReleaseGroupCollection []*ReleaseGroup

// ReleaseGroupCollectionProcessor is a function which modifies each element in a ReleaseGroupCollection
// (typically by populting additional data on it)
type ReleaseGroupCollectionProcessor func(DB, ReleaseGroupCollection) error

// Select adjusts the columns returned from the query
func (q ReleaseGroupQuery) Select(columns string) ReleaseGroupQuery {
	q.builder = q.builder.Select(columns)
	return q
}

// Where adds an additional where clause to the query
func (q ReleaseGroupQuery) Where(cmd string, args ...interface{}) ReleaseGroupQuery {
	q.builder = q.builder.Where(cmd, args...)
	return q
}

// OrderBy adjusts the ordering criteria for the query
func (q ReleaseGroupQuery) OrderBy(cmd string) ReleaseGroupQuery {
	q.builder = q.builder.OrderBy(cmd)
	return q
}

// All returns all results from the query
func (q ReleaseGroupQuery) All() (results ReleaseGroupCollection, err error) {
	results = make(ReleaseGroupCollection, 0)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ReleaseGroupQuery.All() failed to populate ReleaseGroupCollection.")
		return
	}
	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ReleaseGroupCollection.")
		}
	}
	return
}

// One returns a single result from the query
func (q ReleaseGroupQuery) One() (result *ReleaseGroup, err error) {
	results := make(ReleaseGroupCollection, 0, 1)
	err = Select(q.db, &results, q.builder)
	if err != nil {
		err = errors.Wrap(err, "ReleaseGroupQuery.One() failed to populate initial result set.")
		return
	}

	for _, f := range q.processors {
		err = f(q.db, results)
		if err != nil {
			err = errors.Wrap(err, "Failed to run processor over ReleaseGroupCollection.")
			return
		}
	}

	if len(results) > 0 {
		result = results[0]
	}

	return result, nil
}
